package core

import (
	"encoding/json"
	"errors"
	"os"
	"reflect"
	"sort"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/google/uuid"
)

var (
	ModelDoesNotExist          = errors.New("Model does not exist")
	AttributeDoesNotExist      = errors.New("Attribute does not exist")
	AttributeCouldNotBeChanged = errors.New("Attribute couldn't be changed")
	UnalignedAttributeType     = errors.New("The type of value is not consistent with the field type")
)

type Collection[PrimaryKeyT comparable, StructT any] struct {
	data map[PrimaryKeyT]*StructT

	activeElement map[PrimaryKeyT]bool

	mutex sync.RWMutex

	cachedAttribute        map[string]reflect.StructField
	cachedIdAttributeField reflect.StructField
	cachedCreatedAtField   reflect.StructField
	cachedUpdatedAtField   reflect.StructField

	// counter is only used by GenIdFun. Not for counting the number of element in Collection
	counter int

	// Hook is used to register the callback function before and after the Create, Update, Delete operation.
	Hook HookEntry[StructT]

	// SetIdFunc should tell the collection how to set an id. aka, set to which field
	SetIdFunc func(*StructT, PrimaryKeyT)
	// GetIdFunc should tell which field is the id field, and how to get the id value.
	GetIdFunc func(*StructT) PrimaryKeyT
	// GenIdFunc should tell how to generate a new id. And this is call when a model being `Added` into the collection.
	GenIdFunc func(*StructT) PrimaryKeyT
}

type UUIDCollection[T any] = Collection[string, T]
type AutoIncrementCollection[T any] = Collection[int, T]

// QueryBuilder follows the builder pattern to build a query with chained conditions, and finally execute the query to get the result.
type QueryBuilder[PrimaryKeyT comparable, StructT any] struct {
	collection *Collection[PrimaryKeyT, StructT]

	withSoftDeleted bool
	// queued condition filters
	conditions []func(*StructT) bool

	// for pagination
	limit  int
	offset int

	// order
	orderBy        string
	orderDirection string
}

// PaginationResult is the return type of GetWithPagination()
type PaginationResult[T any] struct {
	Data       []*T `json:"data"`
	Total      int  `json:"total"`
	Page       int  `json:"page"`
	PageSize   int  `json:"page_size"`
	TotalPages int  `json:"total_pages"`
	HasNext    bool `json:"has_next"`
}

type BeforeCreateFunc[T any] func(obj *T) error
type AfterCreateFunc[T any] func(obj *T) error

// BeforeUpdateFunc will be used for either UpdateWithObject / UpdateWIthAttributes,
// but the requestObj and requestAttribute will be nil for the UpdateWithAttributes, and UpdateWithObject respectively.
// So that the hook function can know which type of update is being called.
type BeforeUpdateFunc[T any] func(obj *T, requestObj *T, requestAttribute map[string]any) error
type AfterUpdateFunc[T any] func(obj *T) error

type BeforeRemoveFunc[T any] func(obj *T) error
type AfterRemoveFunc[T any] func(obj *T) error

type SnapShot[PrimaryKeyT comparable, StructT any] struct {
	Data          map[PrimaryKeyT]*StructT `json:"data"`
	ActiveElement map[PrimaryKeyT]bool     `json:"active_element"`
	Name          string                   `json:"name"`
	Time          time.Time                `json:"time"`
	Counter       int                      `json:"counter"`
}

func NewCollection[PrimaryKeyT comparable, StructT any]() *Collection[PrimaryKeyT, StructT] {
	c := &Collection[PrimaryKeyT, StructT]{data: make(map[PrimaryKeyT]*StructT)}
	c.cachedAttribute = make(map[string]reflect.StructField)
	c.activeElement = make(map[PrimaryKeyT]bool)

	// start the reflection work here.
	var temp StructT
	t := reflect.TypeOf(temp)
	if t.Kind() == reflect.Ptr {
		t = t.Elem()
	}

	// build SetId, GetId, GenId. And cached the field
	for i := 0; i < t.NumField(); i++ {
		field := t.Field(i)
		c.cachedAttribute[field.Name] = field
		fieldIndex := i

		// `ez:"id:{auto_increment||uuid}"`
		// `ez:"time:{created_at||updated_at}"`
		tag := field.Tag.Get("ez")

		if strings.Contains(tag, "id") {
			// check on is id field type equals to PrimaryKeyT, otherwise panic.
			if field.Type.Kind() != reflect.TypeOf((*PrimaryKeyT)(nil)).Elem().Kind() {
				panic("the type of id field should be the same as PrimaryKeyT")
			}

			c.cachedIdAttributeField = field

			// SetIdFunc, GetIdFun, GenIdFunc will either be generated by reflection
			// (expect we can find the id field by reflection, or else panic)
			// or User defined. In both way, this should not cause any error.

			c.SetIdFunc = func(s *StructT, newId PrimaryKeyT) {
				v := reflect.ValueOf(s)
				if v.Kind() == reflect.Ptr {
					v = v.Elem()
				}

				v.Field(fieldIndex).Set(reflect.ValueOf(newId))
			}

			c.GetIdFunc = func(s *StructT) PrimaryKeyT {
				v := reflect.ValueOf(s)
				if v.Kind() == reflect.Ptr {
					v = v.Elem()
				}

				return any(v.Field(fieldIndex).Interface()).(PrimaryKeyT)
			}

			// switching between auto_increment and uuid
			if strings.Contains(tag, "auto_increment") {
				// assert that PrimaryKeyT is able to incrementally increase, otherwise panic.
				kind := reflect.TypeOf((*PrimaryKeyT)(nil)).Elem().Kind()

				switch kind {
				case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64,
					reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64,
					reflect.Float32, reflect.Float64, reflect.String:
				default:
					panic("PrimaryKeyT should be an incremental type when using auto_increment tag")
				}

				// in here, we assume that PrimaryKeyT is incremental-able
				// Decide conversion strategy once during initialization
				if kind == reflect.String {
					// String-specific GenIdFunc (no runtime check needed)
					c.GenIdFunc = func(s *StructT) PrimaryKeyT {
						c.counter++
						return any(strconv.Itoa(c.counter)).(PrimaryKeyT)
					}
				} else {
					// Numeric-specific GenIdFunc (no runtime check needed)
					c.GenIdFunc = func(s *StructT) PrimaryKeyT {
						c.counter++
						return any(c.counter).(PrimaryKeyT)
					}
				}
			}
			if strings.Contains(tag, "uuid") {
				// only string type is okay
				if field.Type.Kind() != reflect.String {
					panic("the type of uuid field should be the same as PrimaryKeyT")
				}

				c.GenIdFunc = func(s *StructT) PrimaryKeyT {
					newUuid := uuid.New()
					return any(newUuid.String()).(PrimaryKeyT)
				}
			}

		}

		if strings.Contains(tag, "time") || strings.Contains(tag, "timestamp") {
			// created_at / updated_at
			if strings.Contains(tag, "created_at") {
				c.cachedCreatedAtField = field
				c.RegisterBeforeCreateHook(func(obj *StructT) error {
					v := reflect.ValueOf(obj)
					if v.Kind() == reflect.Ptr {
						v = v.Elem()
					}

					v.FieldByIndex(c.cachedCreatedAtField.Index).Set(reflect.ValueOf(time.Now()))

					return nil
				})
			} else if strings.Contains(tag, "updated_at") {
				c.cachedUpdatedAtField = field

				// Also set updated_at on create
				c.RegisterBeforeCreateHook(func(obj *StructT) error {
					v := reflect.ValueOf(obj)
					if v.Kind() == reflect.Ptr {
						v = v.Elem()
					}

					v.FieldByIndex(c.cachedUpdatedAtField.Index).Set(reflect.ValueOf(time.Now()))
					return nil
				})

				// And update it on every update
				c.RegisterAfterUpdateHook(func(obj *StructT) error {
					v := reflect.ValueOf(obj)
					if v.Kind() == reflect.Ptr {
						v = v.Elem()
					}

					v.FieldByIndex(c.cachedUpdatedAtField.Index).Set(reflect.ValueOf(time.Now()))
					return nil
				})
			}
		}
	}
	// end of the reflection work

	// If there are no id field found, panic directly, because the collection can not work without id field.
	if c.SetIdFunc == nil || c.GetIdFunc == nil || c.GenIdFunc == nil {
		panic("No id field found in the struct, please add a field with tag `ez:\"id:{auto_increment||uuid}\"` to specify the id field")
	}

	c.RegisterAfterCreateHook(func(obj *StructT) error {
		c.activeElement[c.GetIdFunc(obj)] = true
		return nil
	})

	return c
}

func NewUUIDCollection[StructT any]() *UUIDCollection[StructT] {
	return NewCollection[string, StructT]()
}

// Add adds the value to the collection immediately. *Always* Gen a new id instead of using defined id.
func (collection *Collection[PrimaryKeyT, StructT]) Add(elem *StructT) error {
	collection.mutex.Lock()
	defer collection.mutex.Unlock()

	newId := collection.GenIdFunc(elem)
	collection.SetIdFunc(elem, newId)

	for _, hook := range collection.Hook.BeforeCreateHooks {
		if err := hook(elem); err != nil {
			return err
		}
	}

	collection.data[newId] = elem

	for _, hook := range collection.Hook.AfterCreateHooks {
		if err := hook(elem); err != nil {
			return err
		}
	}

	return nil
}

// Remove the element from the collection immediately.
func (collection *Collection[PrimaryKeyT, StructT]) Remove(id PrimaryKeyT) error {
	collection.mutex.Lock()
	defer collection.mutex.Unlock()

	elem, ok := collection.data[id]

	if !ok {
		return ModelDoesNotExist
	}

	for _, hook := range collection.Hook.BeforeRemoveHooks {
		if err := hook(elem); err != nil {
			return err
		}
	}

	delete(collection.data, id)
	delete(collection.activeElement, id)

	for _, hook := range collection.Hook.AfterRemoveHooks {
		if err := hook(elem); err != nil {
			return err
		}
	}

	return nil
}

// SoftRemove Soft delete - keeps data, just marks inactive
func (collection *Collection[PrimaryKeyT, StructT]) SoftRemove(id PrimaryKeyT) error {
	collection.mutex.Lock()
	defer collection.mutex.Unlock()

	elem, ok := collection.data[id]
	if !ok {
		return ModelDoesNotExist
	}

	// Run hooks
	for _, hook := range collection.Hook.BeforeRemoveHooks {
		if err := hook(elem); err != nil {
			return err
		}
	}

	// Only mark as deleted, don't remove from data!
	collection.activeElement[id] = false

	for _, hook := range collection.Hook.AfterRemoveHooks {
		if err := hook(elem); err != nil {
			return err
		}
	}

	return nil
}

// GetById is a wrapper of GetByIdWithPointer. There are a version GetWithValue that returns a copy of the element instead.
// Pls noticed that this function able to return 'soft deleted' object.
func (collection *Collection[PrimaryKeyT, StructT]) GetById(id PrimaryKeyT, withSoftDeleted ...bool) (*StructT, error) {
	return collection.GetByIdWithPointer(id, withSoftDeleted...)
}

// GetByIdWithPointer returns a pointer to the value in the collection, and a boolean indicating whether the value exists or not.
func (collection *Collection[PrimaryKeyT, StructT]) GetByIdWithPointer(id PrimaryKeyT, withSoftDeleted ...bool) (*StructT, error) {
	collection.mutex.RLock()
	defer collection.mutex.RUnlock()

	elem, ok := collection.data[id]
	if !ok {
		return nil, ModelDoesNotExist
	}

	// Default: exclude soft-deleted (withSoftDeleted defaults to false)
	_withSoftDeleted := len(withSoftDeleted) > 0 && withSoftDeleted[0]
	if !_withSoftDeleted && !collection.activeElement[id] {
		return nil, ModelDoesNotExist
	}
	return elem, nil
}

// GetByIdWithCopy is the same as GetWithPointer, but it returns a copy of the value instead of a pointer.
// So that the caller can not modify the value in the collection directly.
// GetByIdWithCopy returns a deep copy of the value in the collection
func (collection *Collection[PrimaryKeyT, StructT]) GetByIdWithCopy(id PrimaryKeyT, withSoftDeleted ...bool) (StructT, error) {
	collection.mutex.RLock()
	defer collection.mutex.RUnlock()

	elem, ok := collection.data[id]
	if !ok || elem == nil {
		var zero StructT
		return zero, ModelDoesNotExist
	}

	_withSoftDeleted := len(withSoftDeleted) > 0 && withSoftDeleted[0]
	if !_withSoftDeleted && !collection.activeElement[id] {
		var zero StructT
		return zero, ModelDoesNotExist
	}

	// Deep copy using reflection
	elemValue := reflect.ValueOf(*elem)
	copiedValue := deepCopyValue(elemValue)

	return copiedValue.Interface().(StructT), nil
}

// Update the element with provided element. It just copies the value from source to the target element ( provided PrimaryT ).
func (collection *Collection[PrimaryKeyT, StructT]) Update(id PrimaryKeyT, source StructT, withSoftDeleted ...bool) error {
	collection.mutex.Lock()
	defer collection.mutex.Unlock()

	target, ok := collection.data[id]
	if !ok {
		return ModelDoesNotExist
	}
	// Default: exclude soft-deleted (withSoftDeleted defaults to false)
	_withSoftDeleted := len(withSoftDeleted) > 0 && withSoftDeleted[0]
	if !_withSoftDeleted && !collection.activeElement[id] {
		return ModelDoesNotExist
	}

	for _, hook := range collection.Hook.BeforeUpdateHooks {
		if err := hook(target, &source, nil); err != nil {
			return err
		}
	}

	// deep copy the source to target, but don't change the id or created_at
	sourceValue := reflect.ValueOf(source)
	targetValue := reflect.ValueOf(target).Elem()

	for i := 0; i < targetValue.NumField(); i++ {
		field := targetValue.Field(i)

		// skip the id field and createdAt field using reflection
		if collection.cachedIdAttributeField.Index[0] == i {
			continue
		}

		// skip the createdAt field to prevent overwriting creation timestamp
		if len(collection.cachedCreatedAtField.Index) > 0 && collection.cachedCreatedAtField.Index[0] == i {
			continue
		}

		if field.Kind() == reflect.Ptr {
			field = field.Elem()
		}

		if field.CanSet() {
			field.Set(deepCopyValue(sourceValue.Field(i)))
		}

	}

	for _, hook := range collection.Hook.AfterUpdateHooks {
		if err := hook(target); err != nil {
			return err
		}
	}

	return nil
}

// UpdateWithAttributes updates the element with the given id by the attributes in the map.
// The `attributes` should be the { fieldName : newValue } pair.
func (collection *Collection[PrimaryKeyT, StructT]) UpdateWithAttributes(
	id PrimaryKeyT, attributes map[string]interface{}, withSoftDeleted ...bool) error {
	collection.mutex.Lock()
	defer collection.mutex.Unlock()

	elem, ok := collection.data[id]
	if !ok {
		return ModelDoesNotExist
	}
	// Default: exclude soft-deleted (withSoftDeleted defaults to false)
	_withSoftDeleted := len(withSoftDeleted) > 0 && withSoftDeleted[0]
	if !_withSoftDeleted && !collection.activeElement[id] {
		return ModelDoesNotExist
	}

	// PHASE 1: CALL BEFORE UPDATE HOOKS
	for _, hook := range collection.Hook.BeforeUpdateHooks {
		if err := hook(elem, nil, attributes); err != nil {
			return err
		}
	}

	// PHASE 2: VALIDATE ALL FIELDS (read-only)
	for key, value := range attributes {
		field, ok := collection.cachedAttribute[key]
		if !ok {
			return AttributeDoesNotExist
		}

		if collection.cachedIdAttributeField.Name == field.Name {
			return AttributeCouldNotBeChanged
		}

		v := reflect.ValueOf(elem)
		if v.Kind() == reflect.Ptr {
			v = v.Elem()
		}

		elemField := v.FieldByIndex(field.Index)

		if !elemField.CanSet() {
			return AttributeCouldNotBeChanged
		}

		if elemField.Type() != reflect.TypeOf(value) {
			return UnalignedAttributeType
		}
	}

	// PHASE 3: APPLY ALL CHANGES (if validation and hooks passed)
	for key, value := range attributes {
		field := collection.cachedAttribute[key]
		v := reflect.ValueOf(elem)
		if v.Kind() == reflect.Ptr {
			v = v.Elem()
		}
		elemField := v.FieldByIndex(field.Index)
		elemField.Set(reflect.ValueOf(value))
	}

	for _, hook := range collection.Hook.AfterUpdateHooks {
		if err := hook(elem); err != nil {
			return err
		}
	}

	return nil
}

// AddOrUpdate perform the upsert operation
func (collection *Collection[PrimaryKeyT, StructT]) AddOrUpdate(elem *StructT) error {
	id := collection.GetIdFunc(elem)
	_, err := collection.GetById(id)

	if errors.Is(err, ModelDoesNotExist) {
		return collection.Add(elem)
	}

	return collection.Update(id, *elem)
}

// Count return the length of the Collection
func (collection *Collection[PrimaryKeyT, StructT]) Count(withSoftDeleted ...bool) int {
	collection.mutex.Lock()
	defer collection.mutex.Unlock()

	if len(withSoftDeleted) > 0 && withSoftDeleted[0] {
		return len(collection.activeElement)
	}

	count := 0
	for k, _ := range collection.activeElement {
		if collection.activeElement[k] {
			count++
		}
	}
	return count
}

// Contains return is the element with the given id exists in the collection or not.
// Same as Get, able to
func (collection *Collection[PrimaryKeyT, StructT]) Contains(id PrimaryKeyT, withSoftDeleted ...bool) bool {
	collection.mutex.Lock()
	defer collection.mutex.Unlock()

	if len(withSoftDeleted) > 0 && withSoftDeleted[0] {
		return collection.data[id] != nil
	}

	return collection.activeElement[id] == true && collection.data[id] != nil
}

// List return the data in the collection as an array
func (collection *Collection[PrimaryKeyT, StructT]) List(withSoftDeleted ...bool) []*StructT {
	collection.mutex.RLock()
	defer collection.mutex.RUnlock()

	_withSoftDeleted := false

	if len(withSoftDeleted) > 0 && withSoftDeleted[0] {
		_withSoftDeleted = true
	}

	result := make([]*StructT, 0, len(collection.data))
	for k, elem := range collection.data {
		if !_withSoftDeleted && !collection.activeElement[k] {
			continue
		}
		result = append(result, elem)
	}

	return result

}

// Clear the data. The counter won't be reset for the ID generation
func (collection *Collection[PrimaryKeyT, StructT]) Clear() {
	collection.mutex.Lock()
	defer collection.mutex.Unlock()

	collection.data = make(map[PrimaryKeyT]*StructT)
	collection.activeElement = make(map[PrimaryKeyT]bool)

}

// Query return you a QueryBuilder for chaining query conditions, and finally execute the query to get the result.
func (collection *Collection[PrimaryKeyT, StructT]) Query() *QueryBuilder[PrimaryKeyT, StructT] {
	return &QueryBuilder[PrimaryKeyT, StructT]{
		collection:      collection,
		conditions:      make([]func(*StructT) bool, 0),
		limit:           -1, // No limit by default
		offset:          0,
		withSoftDeleted: false,
	}
}

// SnapShot create a deep copy snapshot of current collection state.
func (collection *Collection[PrimaryKeyT, StructT]) SnapShot() *SnapShot[PrimaryKeyT, StructT] {
	collection.mutex.Lock()
	defer collection.mutex.Unlock()

	snapshotData := make(map[PrimaryKeyT]*StructT)
	activeElement := make(map[PrimaryKeyT]bool)
	for k, v := range collection.data {
		copiedValue := deepCopyValue(reflect.ValueOf(*v))
		copiedElem := copiedValue.Interface().(StructT)
		snapshotData[k] = &copiedElem
		activeElement[k] = collection.activeElement[k]
	}

	return &SnapShot[PrimaryKeyT, StructT]{
		Data:          snapshotData,
		ActiveElement: activeElement,
		Time:          time.Now(),
		Counter:       collection.counter,
		Name:          "Snapshot created by ezapi::collection",
	}
}

// Restore the state to what snapshot is.
func (collection *Collection[PrimaryKeyT, StructT]) Restore(snapShot *SnapShot[PrimaryKeyT, StructT]) {
	collection.mutex.Lock()
	defer collection.mutex.Unlock()

	if snapShot == nil {
		return
	}

	collection.data = make(map[PrimaryKeyT]*StructT)
	for k, v := range snapShot.Data {
		copiedValue := deepCopyValue(reflect.ValueOf(*v))
		copiedElem := copiedValue.Interface().(StructT)
		collection.data[k] = &copiedElem
	}

	collection.counter = snapShot.Counter
	collection.activeElement = snapShot.ActiveElement
}

type filterCondition struct {
	field    string
	operator string // expecting "=", "!=", ">", "<", ">=", "<=", "contains"
	value    interface{}
}

// Where adds a field-based filter
func (qb *QueryBuilder[PrimaryKeyT, StructT]) Where(
	field string, operator string, value interface{}) *QueryBuilder[PrimaryKeyT, StructT] {
	qb.conditions = append(qb.conditions, func(s *StructT) bool {
		return qb.matchCondition(s, filterCondition{
			field:    field,
			operator: operator,
			value:    value,
		})
	})
	return qb
}

// WhereWith adds a custom filter function
func (qb *QueryBuilder[PrimaryKeyT, StructT]) WhereWith(
	fn func(*StructT) bool) *QueryBuilder[PrimaryKeyT, StructT] {
	qb.conditions = append(qb.conditions, fn)
	return qb
}

// In is a helper function for Where with "IN" operator, which checks if the field value is in the provided values slice.
func (qb *QueryBuilder[PrimaryKeyT, StructT]) In(field string, values []interface{}) *QueryBuilder[PrimaryKeyT, StructT] {
	qb.conditions = append(qb.conditions, func(s *StructT) bool {
		for _, value := range values {
			if qb.matchCondition(s, filterCondition{
				field:    field,
				operator: "=",
				value:    value,
			}) {
				return true
			}
		}
		return false
	})
	return qb
}

// NotIn - inverse version of In
func (qb *QueryBuilder[PrimaryKeyT, StructT]) NotIn(field string, values []interface{}) *QueryBuilder[PrimaryKeyT, StructT] {
	qb.conditions = append(qb.conditions, func(s *StructT) bool {
		for _, value := range values {
			if qb.matchCondition(s, filterCondition{
				field:    field,
				operator: "=",
				value:    value,
			}) {
				return false
			}
		}

		return true
	})

	return qb
}

func (qb *QueryBuilder[PrimaryKeyT, StructT]) Between(field string, min, max interface{}) *QueryBuilder[PrimaryKeyT, StructT] {
	return qb.Where(field, ">=", min).Where(field, "<=", max)
}

// Limit sets max number of results
func (qb *QueryBuilder[PrimaryKeyT, StructT]) Limit(n int) *QueryBuilder[PrimaryKeyT, StructT] {
	qb.limit = n
	return qb
}

// Offset sets starting position
func (qb *QueryBuilder[PrimaryKeyT, StructT]) Offset(n int) *QueryBuilder[PrimaryKeyT, StructT] {
	qb.offset = n
	return qb
}

func (qb *QueryBuilder[PrimaryKeyT, StructT]) Page(pageNum, pageSize int) *QueryBuilder[PrimaryKeyT, StructT] {
	if pageNum < 1 {
		pageNum = 1
	}
	if pageSize < 1 {
		pageSize = 10
	}
	return qb.Offset((pageNum - 1) * pageSize).Limit(pageSize)
}

// OrderBy sets sorting field and direction
func (qb *QueryBuilder[PrimaryKeyT, StructT]) OrderBy(
	field string, direction string) *QueryBuilder[PrimaryKeyT, StructT] {
	qb.orderBy = field
	qb.orderDirection = direction
	return qb
}

func (qb *QueryBuilder[PrimaryKeyT, StructT]) WithSoftDeleted() *QueryBuilder[PrimaryKeyT, StructT] {
	qb.withSoftDeleted = true
	return qb
}

// below is execution functions for the query builder

// Get executes the query and returns matching elements
func (qb *QueryBuilder[PrimaryKeyT, StructT]) Get() []*StructT {
	qb.collection.mutex.RLock()
	defer qb.collection.mutex.RUnlock()

	results := make([]*StructT, 0)

	// Iterate through all elements
	for k, v := range qb.collection.data {
		elem := v

		// Skip soft deleted if not included
		if !qb.withSoftDeleted && !qb.collection.activeElement[k] {
			continue
		}

		if qb.matches(elem) {
			results = append(results, elem)
		}
	}

	// Apply sorting
	if qb.orderBy != "" {
		qb.sort(results)
	}

	// Apply offset and limit
	start := qb.offset
	if start > len(results) {
		return []*StructT{}
	}

	end := len(results)
	if qb.limit > 0 && start+qb.limit < end {
		end = start + qb.limit
	}

	return results[start:end]
}

// GetWithPagination - Get with PaginationResult
func (qb *QueryBuilder[PrimaryKeyT, StructT]) GetWithPagination() *PaginationResult[StructT] {
	results := qb.Get()
	total := qb.Count()

	pageSize := qb.limit
	if pageSize <= 0 {
		pageSize = total
	}

	pageNum := (qb.offset / pageSize) + 1
	totalPages := (total + pageSize - 1) / pageSize

	return &PaginationResult[StructT]{
		Data:       results,
		Total:      total,
		Page:       pageNum,
		PageSize:   pageSize,
		TotalPages: totalPages,
		HasNext:    pageNum < totalPages,
	}
}

// Results - simply a alias of Get()
func (qb *QueryBuilder[PrimaryKeyT, StructT]) Results() []*StructT {
	return qb.Get()
}

// First returns the first matching element
func (qb *QueryBuilder[PrimaryKeyT, StructT]) First() (*StructT, bool) {
	results := qb.Limit(1).Get()
	if len(results) == 0 {
		return nil, false
	}
	return results[0], true
}

// FirstOrDefault returns the first matching element or else default StructT object
func (qb *QueryBuilder[PrimaryKeyT, StructT]) FirstOrDefault() *StructT {
	results, okay := qb.First()
	if !okay {
		var zero StructT
		return &zero
	}

	return results
}

// Count returns number of matching elements
func (qb *QueryBuilder[PrimaryKeyT, StructT]) Count() int {
	qb.collection.mutex.RLock()
	defer qb.collection.mutex.RUnlock()

	count := 0
	for _, elem := range qb.collection.data {
		if qb.matches(elem) {
			count++
		}
	}
	return count
}

// Exists checks if any element matches
func (qb *QueryBuilder[PrimaryKeyT, StructT]) Exists() bool {
	return qb.Count() > 0
}

// below is the start of helper function used in query builder

// matches checks if element satisfies all conditions
func (qb *QueryBuilder[PrimaryKeyT, StructT]) matches(elem *StructT) bool {
	// Check custom filter functions
	for _, fn := range qb.conditions {
		if !fn(elem) {
			return false
		}
	}

	return true
}

// matchCondition checks a single field condition
func (qb *QueryBuilder[PrimaryKeyT, StructT]) matchCondition(
	elem *StructT, cond filterCondition) bool {

	// Get field value using reflection
	v := reflect.ValueOf(elem)
	if v.Kind() == reflect.Ptr {
		v = v.Elem()
	}

	field, ok := qb.collection.cachedAttribute[cond.field]
	if !ok {
		return false
	}

	fieldValue := v.FieldByIndex(field.Index).Interface()

	// Compare based on operator
	switch cond.operator {
	case "=", "==":
		return reflect.DeepEqual(fieldValue, cond.value)
	case "!=":
		return !reflect.DeepEqual(fieldValue, cond.value)
	case ">":
		return compare(fieldValue, cond.value) > 0
	case "<":
		return compare(fieldValue, cond.value) < 0
	case ">=":
		return compare(fieldValue, cond.value) >= 0
	case "<=":
		return compare(fieldValue, cond.value) <= 0
	case "contains":
		return contains(fieldValue, cond.value)
	default:
		return false
	}
}

// compare for numeric/string comparison
func compare(a, b interface{}) int {
	// Handle different types
	switch v := a.(type) {
	case int:
		if bVal, ok := b.(int); ok {
			if v < bVal {
				return -1
			}
			if v > bVal {
				return 1
			}
			return 0
		}
	case string:
		if bVal, ok := b.(string); ok {
			if v < bVal {
				return -1
			}
			if v > bVal {
				return 1
			}
			return 0
		}
	case float64:
		if bVal, ok := b.(float64); ok {
			if v < bVal {
				return -1
			}
			if v > bVal {
				return 1
			}
			return 0
		}
		// Add more types as needed
	}
	return 0
}

// contains for string contains check
func contains(haystack, needle interface{}) bool {
	h, ok1 := haystack.(string)
	n, ok2 := needle.(string)
	if ok1 && ok2 {
		return strings.Contains(h, n)
	}
	return false
}

// sort results by field
func (qb *QueryBuilder[PrimaryKeyT, StructT]) sort(results []*StructT) {
	field, ok := qb.collection.cachedAttribute[qb.orderBy]
	if !ok {
		return
	}

	sort.Slice(results, func(i, j int) bool {
		vi := reflect.ValueOf(results[i]).Elem().FieldByIndex(field.Index).Interface()
		vj := reflect.ValueOf(results[j]).Elem().FieldByIndex(field.Index).Interface()

		cmp := compare(vi, vj)
		if qb.orderDirection == "desc" {
			return cmp > 0
		}
		return cmp < 0
	})
}

// below is start of Hook event

// HookEntry is just a simple struct that holds all the hook events.
// If want to make it better, might add mutex for registering hooks,
// but currently we assume that the hook registration is only done in the initialization phase (kinda static anyway)
// and will not be changed after that. So we don't add mutex for it.
type HookEntry[T any] struct {
	BeforeCreateHooks []BeforeCreateFunc[T]
	AfterCreateHooks  []AfterCreateFunc[T]

	BeforeUpdateHooks []BeforeUpdateFunc[T]
	AfterUpdateHooks  []AfterUpdateFunc[T]

	BeforeRemoveHooks []BeforeRemoveFunc[T]
	AfterRemoveHooks  []AfterRemoveFunc[T]
}

func (collection *Collection[PrimaryKeyT, StructT]) RegisterBeforeCreateHook(hook BeforeCreateFunc[StructT]) {
	collection.Hook.BeforeCreateHooks = append(collection.Hook.BeforeCreateHooks, hook)
}

func (collection *Collection[PrimaryKeyT, StructT]) RegisterAfterCreateHook(hook AfterCreateFunc[StructT]) {
	collection.Hook.AfterCreateHooks = append(collection.Hook.AfterCreateHooks, hook)
}

func (collection *Collection[PrimaryKeyT, StructT]) RegisterBeforeUpdateHook(hook BeforeUpdateFunc[StructT]) {
	collection.Hook.BeforeUpdateHooks = append(collection.Hook.BeforeUpdateHooks, hook)
}

func (collection *Collection[PrimaryKeyT, StructT]) RegisterAfterUpdateHook(hook AfterUpdateFunc[StructT]) {
	collection.Hook.AfterUpdateHooks = append(collection.Hook.AfterUpdateHooks, hook)
}

func (collection *Collection[PrimaryKeyT, StructT]) RegisterBeforeRemoveHook(hook BeforeRemoveFunc[StructT]) {
	collection.Hook.BeforeRemoveHooks = append(collection.Hook.BeforeRemoveHooks, hook)
}

func (collection *Collection[PrimaryKeyT, StructT]) RegisterAfterRemoveHook(hook AfterRemoveFunc[StructT]) {
	collection.Hook.AfterRemoveHooks = append(collection.Hook.AfterRemoveHooks, hook)
}

// SaveAsJson will save the snapshot as JSON with the given file path.
// The JSON file will contain the timestamp, name, counter and the data in the snapshot.
func (s *SnapShot[PrimaryKeyT, StructT]) SaveAsJson(filePath string) error {
	data, err := json.Marshal(s)
	if err != nil {
		return err
	}

	return os.WriteFile(filePath, data, 0644)
}

func (s *SnapShot[PrimaryKeyT, StructT]) LoadFromJson(filePath string) error {

	// Read the JSON file
	fileData, err := os.ReadFile(filePath)
	if err != nil {
		return err
	}

	err = json.Unmarshal(fileData, &s)
	if err != nil {
		return err
	}

	return nil
}

// helper function to provide deep copy

// deepCopyValue performs a deep copy of a reflect.Value
func deepCopyValue(src reflect.Value) reflect.Value {
	switch src.Kind() {
	case reflect.Slice:
		if src.IsNil() {
			return src
		}
		// Create a new slice with same length and capacity
		dst := reflect.MakeSlice(src.Type(), src.Len(), src.Cap())
		// Deep copy each element
		for i := 0; i < src.Len(); i++ {
			dst.Index(i).Set(deepCopyValue(src.Index(i)))
		}
		return dst

	case reflect.Map:
		if src.IsNil() {
			return src
		}
		// Create a new map
		dst := reflect.MakeMap(src.Type())
		// Deep copy each key-value pair
		for _, key := range src.MapKeys() {
			dst.SetMapIndex(key, deepCopyValue(src.MapIndex(key)))
		}
		return dst

	case reflect.Ptr:
		if src.IsNil() {
			return src
		}
		// Create a new pointer and deep copy the value it points to
		dst := reflect.New(src.Type().Elem())
		dst.Elem().Set(deepCopyValue(src.Elem()))
		return dst

	case reflect.Struct:
		// Create a new struct and deep copy all fields
		dst := reflect.New(src.Type()).Elem()
		for i := 0; i < src.NumField(); i++ {
			if dst.Field(i).CanSet() {
				dst.Field(i).Set(deepCopyValue(src.Field(i)))
			}
		}
		return dst

	case reflect.Array:
		// Create a new array and deep copy all elements
		dst := reflect.New(src.Type()).Elem()
		for i := 0; i < src.Len(); i++ {
			dst.Index(i).Set(deepCopyValue(src.Index(i)))
		}
		return dst

	default:
		// For primitive types (int, string, bool, float, etc.), just return the value
		return src
	}
}
